default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4 # Check for latest version: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terragrunt_fmt
      - id: terragrunt_validate
      - id: terragrunt_validate_inputs
      - id: terragrunt_providers_lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Check for latest version: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
